services:
  # BASE DE DATOS
  database:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data/:/var/lib/postgresql/data
      - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql  # Montar el archivo data.sql para inicializar la base de datos
    networks:
      - dmz

  #------------------------------FIREWALL-----------------------
  firewall:
    build:
      context: firewall
      dockerfile: Dockerfile
    container_name: fw
    environment:
      - IP_CLIENT=10.40.1.6
    networks:
      - dmz
      - lan
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1 #Permite que el FW enrute entre redes
    ports:
      - 4000:4000
      - 80:80
    
    #--------------------------Contenedor para el servicio web--------------
  
  frontend:
    build:
      context: client
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - firewall
    environment:
      - NODE_ENV=development
    networks:
      dmz:
        ipv4_address: 10.40.1.6

  # BACKEND
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    container_name: server
    networks:
      - dmz
    depends_on:
      - firewall

networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_DMZ}
  
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_LAN}
