version: '3.8'

services:
  #BASE DE DATOS
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data/:/var/lib/postgresql/data
    networks:
      - dmz
    expose:
      - "5432:5432"
  
  #------------------------------FIREWALL-----------------------
  firewall:
    build:
      context: firewall
      dockerfile: Dockerfile
    container_name: firewall
    networks:
      - dmz
      - lan
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1 #Permite que el FW enrute entre redes
    
    #--------------------------Contenedor para el servicio web--------------
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Cambia el puerto según la configuración
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: always  # Opcional: reiniciar el contenedor automáticamente si falla
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Cambia el puerto según tu configuración
    depends_on:
      - backend

networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_DMZ}
  
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_LAN}
