services:
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data/:/var/lib/postgresql/data
    networks:
      - dmz
    ports:
      - 5432:5432
  
  firewall:
    build:
      context: firewall
      dockerfile: Dockerfile
    container_name: firewall
    networks:
      - dmz
      - lan


networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_DMZ}
  
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_LAN}