version: '3.8'

services:
  #BASE DE DATOS
  database:
    build:
      context: database
      dockerfile: Dockerfile
    container_name: database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data/:/var/lib/postgresql/data
    networks:
      - dmz
    expose:
      - "3306"
  
  #------------------------------FIREWALL-----------------------
  firewall:
    build:
      context: firewall
      dockerfile: Dockerfile
    container_name: firewall
    networks:
      - dmz
      - lan
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1 #Permite que el FW enrute entre redes
    ports:
      - 5000:5000
    
    #--------------------------Contenedor para el servicio web--------------
  frontend:
    build: # Imagen de tu aplicación web
      context: client
      dockerfile: Dockerfile
    networks:
      - dmz
    depends_on:
      - firewall # Asegura que el firewall se inicie antes
    expose:
      - "443"

  backend:
    build:
      context: server
      dockerfile: Dockerfile
    networks:
      - dmz
    depends_on:
      - firewall


networks:
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_DMZ}
  
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_LAN}
